### ISSUE TITLE
vars in kastali/.config/polybar/config

### ISSUE THREAD

**Issue by githubedu** [GuardKenzie/kastali#1]
Hi,

thanks for sharing this great piece of art.

I'm trying to configure some parts like the polybar, but struggling to get it working.

I think some of the problem is due to missing the variables defined in this line.
[vars]
include-file = ~/.config/polybar/vars

Could you please advise how these variables are created or share the file?

Thank you

**Comment by GuardKenzie** [comment]
Sorry about the wait. The file is now available with edafa26
